network call internet permission  and gradle dependancies for retrofit
AntoninoAN/restaurants_yelp pull request #7
Opened 2023-01-23 16:30 UTC by gugut-net

Internet access and Gradle updates.

2023-01-23 16:35 UTC, gguij004 approved these changes

2023-01-24 14:19 UTC, AntoninoAN requested changes

2023-01-24 14:19 UTC, AntoninoAN commented on app/src/main/AndroidManifest.xml
> +
Add the location services permission.

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

2023-01-24 14:59 UTC, AntoninoAN approved these changes

2023-01-24 14:59 UTC, gguij004 approved these changes

2023-01-24 15:00 UTC, RAGilesMCS approved these changes

2023-01-24 15:00 UTC, AntoninoAN approved these changes

2023-01-24 15:04 UTC, merged